# 1. Numpy 실습
- 18_데이터분석_NumPy.pdf - 실습 4, 6, 8, 11, 13, 15

## setup

In [29]:
import numpy as np

## 실습 4

In [38]:
arr = np.array([-10, 20, 0, -30, 10, 50])
arr[arr<0] = 0
print(arr)

[ 0 20  0  0 10 50]


## 실습 8

In [70]:
def make_array(n, m):
    arr = np.arange(1, n * m + 1)
    arr = arr.reshape(n, m)
    return arr

print(make_array(2, 3))

[[1 2 3]
 [4 5 6]]


## 실습 11

In [74]:
arr = np.array([-10, 20, 0, -30, 10, 50])
arr[arr<0] = arr[arr<0] * (-1)
print(arr)

[10 20  0 30 10 50]


## 실습 13

In [80]:
mid_score = np.array([90, 100, 85, 60, 75])
final_score = np.array([80, 90, 75, 50, 55])

ave_score = (mid_score + final_score) / 2

merged_score = np.vstack((mid_score, final_score, ave_score))
print(merged_score)

[[ 90. 100.  85.  60.  75.]
 [ 80.  90.  75.  50.  55.]
 [ 85.  95.  80.  55.  65.]]


## 실습 15

- driver launch

In [138]:
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager

# find_elements 사용을 위해 필요
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys

def find(css_selector):
    return driver.find_element(By.CSS_SELECTOR, css_selector)

def finds(css_selector):
    return driver.find_elements(By.CSS_SELECTOR, css_selector)

def element_find(element, css_selector):
    return element.find_element(By.CSS_SELECTOR, css_selector)

def element_finds(element, css_selector):
    return element.find_elements(By.CSS_SELECTOR, css_selector)

service = Service(ChromeDriverManager().install())
driver = webdriver.Chrome(service=service)
driver.implicitly_wait(10)  

- 날짜별로 승률 테이블 가져오기

In [142]:
import time 
# 팀 순위 페이지 접속
driver.get('https://www.koreabaseball.com/Record/TeamRank/TeamRankDaily.aspx')


# 날짜별 승률을 저장하기 위한 리스트
win_rates = list()

while(True):

    # 1. 2025년도 데이터만 추출하기 위헤 날짜 확인
    
    # 1-1. 날짜 추출 
    date = find('span#cphContents_cphContents_cphContents_lblSearchDateTitle').text
    
    # 1-2. 년도 확인하여 2025년이 아니면 종료
    year = int(date.split('.')[0])  # 날짜에서 연도만 추출
    if year != 2025:
        break

    print(f'데이터 수집 - {date}')
    
    
    # 2. 페이지에서 팀명과 승률을 수집하여 win_rates에 저장
    records = finds('#cphContents_cphContents_cphContents_udpRecord > table.tData > tbody > tr')
    win_rate = dict()
    for record in records:
        fields = element_finds(record, 'td')

        #팀명 추출, 2번째 열
        name = fields[1].text
        #승률, 7번째 열
        rate = float(fields[6].text)

        # 수집한 데이터 저장
        #print(name, rate)
        win_rate[name] = rate

    # 날짜 오름차순으로 저장하기 위해 앞에다 삽입
    win_rates.insert(0, win_rate)
    
    # 3. 이전 날짜로 이동하기
    
    # 3-1. 이전 페이지 버튼 찾기
    prev = find('input#cphContents_cphContents_cphContents_btnPreDate')
    prev.click()

    # 3-2. click 후 1초긴 대기, 대기 시간이 없으면, 페이지가 바뀌기 전에 데이터를 추출하게됨
    time.sleep(1)
    
print(win_rates)

데이터 수집 - 2025.04.16
데이터 수집 - 2025.04.15
데이터 수집 - 2025.04.13
데이터 수집 - 2025.04.12
데이터 수집 - 2025.04.11
데이터 수집 - 2025.04.10
데이터 수집 - 2025.04.09
데이터 수집 - 2025.04.08
데이터 수집 - 2025.04.06
데이터 수집 - 2025.04.05
데이터 수집 - 2025.04.04
데이터 수집 - 2025.04.03
데이터 수집 - 2025.04.02
데이터 수집 - 2025.03.30
데이터 수집 - 2025.03.29
데이터 수집 - 2025.03.28
데이터 수집 - 2025.03.27
데이터 수집 - 2025.03.26
데이터 수집 - 2025.03.25
데이터 수집 - 2025.03.23
데이터 수집 - 2025.03.22
[{'KIA': 1.0, '삼성': 1.0, 'LG': 1.0, 'SSG': 1.0, '한화': 1.0, '두산': 0.0, 'KT': 0.0, '롯데': 0.0, 'NC': 0.0, '키움': 0.0}, {'삼성': 1.0, 'LG': 1.0, 'SSG': 1.0, 'KIA': 0.5, 'KT': 0.5, '한화': 0.5, 'NC': 0.5, '두산': 0.0, '롯데': 0.0, '키움': 0.0}, {'삼성': 1.0, 'LG': 1.0, 'KIA': 0.667, 'KT': 0.667, 'SSG': 0.667, '롯데': 0.333, '한화': 0.333, 'NC': 0.333, '두산': 0.0, '키움': 0.0}, {'LG': 1.0, '삼성': 0.75, 'SSG': 0.75, 'KIA': 0.5, 'KT': 0.5, 'NC': 0.5, '두산': 0.25, '롯데': 0.25, '한화': 0.25, '키움': 0.25}, {'LG': 1.0, 'SSG': 0.8, '삼성': 0.6, 'KT': 0.6, 'NC': 0.6, 'KIA': 0.4, '키움': 0.4, '두산': 0.2, '롯데': 0.2, '한화

- 승률 데이터로 부터 ndarray 생성

In [256]:

teams = None
result = None

for win_rate in win_rates:
    
    # win_rate dict를 팀명으로 정렬
    win_rate = sorted(win_rate.items())

    # 정렬된 값에서 승률값으로 ndarray 생성
    teams = [ key for key, value in win_rate ] 
    win_rate = [ value for key, value in win_rate ]
    win_rate = np.array(win_rate)

    # 생성된 array를 열기준으로 합치기
    if result is None:
        result = win_rate
    else:
        result = np.column_stack((result, win_rate))

print(teams)
print(result)

['KIA', 'KT', 'LG', 'NC', 'SSG', '두산', '롯데', '삼성', '키움', '한화']
[[1.    0.5   0.667 0.5   0.4   0.333 0.286 0.375 0.333 0.4   0.364 0.364
  0.333 0.385 0.429 0.4   0.375 0.375 0.412 0.444 0.421]
 [0.    0.5   0.667 0.5   0.6   0.667 0.571 0.571 0.625 0.556 0.5   0.5
  0.455 0.5   0.538 0.5   0.533 0.533 0.563 0.529 0.556]
 [1.    1.    1.    1.    1.    1.    1.    1.    0.875 0.889 0.9   0.9
  0.909 0.917 0.846 0.857 0.867 0.875 0.824 0.833 0.842]
 [0.    0.5   0.333 0.5   0.6   0.5   0.429 0.429 0.429 0.429 0.375 0.444
  0.5   0.455 0.417 0.462 0.429 0.4   0.438 0.438 0.438]
 [1.    1.    0.667 0.75  0.8   0.667 0.571 0.625 0.625 0.625 0.667 0.667
  0.7   0.636 0.667 0.615 0.643 0.643 0.6   0.563 0.529]
 [0.    0.    0.    0.25  0.2   0.333 0.286 0.25  0.333 0.4   0.455 0.417
  0.462 0.5   0.467 0.438 0.412 0.389 0.421 0.421 0.421]
 [0.    0.    0.333 0.25  0.2   0.167 0.286 0.286 0.375 0.444 0.4   0.455
  0.417 0.385 0.357 0.4   0.438 0.471 0.444 0.474 0.5  ]
 [1.    1.    1.    0.75

- 파일로 저장하기

In [170]:
with open('kbo_win_rate.csv', 'w') as f:
    for i, win_rate in enumerate(result):
        team = teams[i]
        win_rate = ','.join(win_rate.astype(str))
        line = team + ',' + win_rate + '\n'
        f.write(line)
        

# 2. Pandas 실습
- 19_데이터분석_Pandas.pdf - 실습 3, 5, 8, 12, 18, 19, 21

## Setup

In [173]:
import pandas as pd

## 실습 3

- Numpy 실습 14 코드

In [209]:
import requests
from bs4 import BeautifulSoup
import numpy as np

# 0. 시작 url
url = "https://www.koreabaseball.com/Record/TeamRank/TeamRankDaily.aspx"

response = requests.get(url)
html = BeautifulSoup(response.text, 'html.parser')

table = html.select_one('#cphContents_cphContents_cphContents_udpRecord > table.tData')
records = html.select('#cphContents_cphContents_cphContents_udpRecord > table.tData > tbody > tr')
rows = list()
for record in records:

    # record에서 필드값을 갖는 요소들을 찾기
    fields = record.select('td')
    
    row = list()
    # 각 요소에서 text 추출
    for field in fields:
        row.append(field.text.strip())

    rows.append(row)

rows[0]

arr = np.array(rows)
print(arr)

[['1' 'LG' '19' '16' '3' '0' '0.842' '0' '8승0무2패' '2승' '11-0-1' '5-0-2']
 ['2' 'KT' '19' '10' '8' '1' '0.556' '5.5' '5승0무5패' '1승' '8-0-4' '2-1-4']
 ['3' 'SSG' '17' '9' '8' '0' '0.529' '6' '5승0무5패' '3패' '6-0-3' '3-0-5']
 ['4' '삼성' '20' '10' '10' '0' '0.500' '6.5' '4승0무6패' '4패' '7-0-4' '3-0-6']
 ['4' '롯데' '21' '10' '10' '1' '0.500' '6.5' '6승0무4패' '2승' '5-1-5' '5-0-5']
 ['6' '한화' '21' '10' '11' '0' '0.476' '7' '7승0무3패' '3승' '4-0-4' '6-0-7']
 ['7' 'NC' '16' '7' '9' '0' '0.438' '7.5' '4승0무6패' '1승' '1-0-4' '6-0-5']
 ['8' 'KIA' '19' '8' '11' '0' '0.421' '8' '5승0무5패' '1패' '5-0-6' '3-0-5']
 ['8' '두산' '19' '8' '11' '0' '0.421' '8' '5승0무5패' '1승' '4-0-4' '4-0-7']
 ['10' '키움' '21' '7' '14' '0' '0.333' '10' '2승0무8패' '3패' '4-0-5' '3-0-9']]


- 7열, 3열 선택

In [221]:
win_rate = arr[:,6].astype(float)
wins = arr[:,3].astype(int)

print(win_rate)
print(wins)

[0.842 0.556 0.529 0.5   0.5   0.476 0.438 0.421 0.421 0.333]
[16 10  9 10 10 10  7  8  8  7]


## 실습 5

In [224]:
win_rate[win_rate>=0.6]

array([0.842])

In [226]:
win_rate[win_rate<0.5] = 0.5
win_rate

array([0.842, 0.556, 0.529, 0.5  , 0.5  , 0.5  , 0.5  , 0.5  , 0.5  ,
       0.5  ])

In [228]:
win_rate[-3:] = 0
win_rate

array([0.842, 0.556, 0.529, 0.5  , 0.5  , 0.5  , 0.5  , 0.   , 0.   ,
       0.   ])

## 실습 8

In [245]:
teams = arr[:,1]
win = arr[:,3].astype(int)
loose = arr[:,4].astype(int)
tie = arr[:,5].astype(int)
win_rate = arr[:,6].astype(float)
last = arr[:,8]
kbo_df = pd.DataFrame({'승': win, '패': loose, '무': tie, '승률': win_rate, '최근10경기': last},
                     index=teams) 
print(kbo_df.dtypes)
kbo_df

승           int64
패           int64
무           int64
승률        float64
최근10경기     object
dtype: object


승   패  무     승률  최근10경기
LG   16   3  0  0.842  8승0무2패
KT   10   8  1  0.556  5승0무5패
SSG   9   8  0  0.529  5승0무5패
삼성   10  10  0  0.500  4승0무6패
롯데   10  10  1  0.500  6승0무4패
한화   10  11  0  0.476  7승0무3패
NC    7   9  0  0.438  4승0무6패
KIA   8  11  0  0.421  5승0무5패
두산    8  11  0  0.421  5승0무5패
키움    7  14  0  0.333  2승0무8패

## 실습 12

In [247]:
kbo_df.loc[['LG', 'KT', '삼성']]

승   패  무     승률  최근10경기
LG  16   3  0  0.842  8승0무2패
KT  10   8  1  0.556  5승0무5패
삼성  10  10  0  0.500  4승0무6패

In [249]:
kbo_df[['승', '패']]

승   패
LG   16   3
KT   10   8
SSG   9   8
삼성   10  10
롯데   10  10
한화   10  11
NC    7   9
KIA   8  11
두산    8  11
키움    7  14

In [251]:
kbo_df.loc[kbo_df['승'] + kbo_df['패'] + kbo_df['무'] >= 18]

승   패  무     승률  최근10경기
LG   16   3  0  0.842  8승0무2패
KT   10   8  1  0.556  5승0무5패
삼성   10  10  0  0.500  4승0무6패
롯데   10  10  1  0.500  6승0무4패
한화   10  11  0  0.476  7승0무3패
KIA   8  11  0  0.421  5승0무5패
두산    8  11  0  0.421  5승0무5패
키움    7  14  0  0.333  2승0무8패

In [253]:
kbo_df.loc[kbo_df['승'] < kbo_df['패']]

승   패  무     승률  최근10경기
한화   10  11  0  0.476  7승0무3패
NC    7   9  0  0.438  4승0무6패
KIA   8  11  0  0.421  5승0무5패
두산    8  11  0  0.421  5승0무5패
키움    7  14  0  0.333  2승0무8패

## 실습 21

- Numpy 실습 15번 코드 복사하여 사용

In [258]:
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager

# find_elements 사용을 위해 필요
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys

def find(css_selector):
    return driver.find_element(By.CSS_SELECTOR, css_selector)

def finds(css_selector):
    return driver.find_elements(By.CSS_SELECTOR, css_selector)

def element_find(element, css_selector):
    return element.find_element(By.CSS_SELECTOR, css_selector)

def element_finds(element, css_selector):
    return element.find_elements(By.CSS_SELECTOR, css_selector)

service = Service(ChromeDriverManager().install())
driver = webdriver.Chrome(service=service)
driver.implicitly_wait(10)  

import time 
# 팀 순위 페이지 접속
driver.get('https://www.koreabaseball.com/Record/TeamRank/TeamRankDaily.aspx')


# 날짜별 승률을 저장하기 위한 리스트
win_rates = list()

while(True):

    # 1. 2025년도 데이터만 추출하기 위헤 날짜 확인
    
    # 1-1. 날짜 추출 
    date = find('span#cphContents_cphContents_cphContents_lblSearchDateTitle').text
    
    # 1-2. 년도 확인하여 2025년이 아니면 종료
    year = int(date.split('.')[0])  # 날짜에서 연도만 추출
    if year != 2025:
        break

    print(f'데이터 수집 - {date}')
    
    
    # 2. 페이지에서 팀명과 승률을 수집하여 win_rates에 저장
    records = finds('#cphContents_cphContents_cphContents_udpRecord > table.tData > tbody > tr')
    win_rate = dict()
    for record in records:
        fields = element_finds(record, 'td')

        #팀명 추출, 2번째 열
        name = fields[1].text
        #승률, 7번째 열
        rate = float(fields[6].text)

        # 수집한 데이터 저장
        #print(name, rate)
        win_rate[name] = rate

    # 날짜 오름차순으로 저장하기 위해 앞에다 삽입
    win_rates.insert(0, win_rate)
    
    # 3. 이전 날짜로 이동하기
    
    # 3-1. 이전 페이지 버튼 찾기
    prev = find('input#cphContents_cphContents_cphContents_btnPreDate')
    prev.click()

    # 3-2. click 후 1초긴 대기, 대기 시간이 없으면, 페이지가 바뀌기 전에 데이터를 추출하게됨
    time.sleep(1)
    
teams = None
result = None

for win_rate in win_rates:
    
    # win_rate dict를 팀명으로 정렬
    win_rate = sorted(win_rate.items())

    # 정렬된 값에서 승률값으로 ndarray 생성
    teams = [ key for key, value in win_rate ] 
    win_rate = [ value for key, value in win_rate ]
    win_rate = np.array(win_rate)

    # 생성된 array를 열기준으로 합치기
    if result is None:
        result = win_rate
    else:
        result = np.column_stack((result, win_rate))

print(teams)
print(result)

데이터 수집 - 2025.04.16
데이터 수집 - 2025.04.15
데이터 수집 - 2025.04.13
데이터 수집 - 2025.04.12
데이터 수집 - 2025.04.11
데이터 수집 - 2025.04.10
데이터 수집 - 2025.04.09
데이터 수집 - 2025.04.08
데이터 수집 - 2025.04.06
데이터 수집 - 2025.04.05
데이터 수집 - 2025.04.04
데이터 수집 - 2025.04.03
데이터 수집 - 2025.04.02
데이터 수집 - 2025.03.30
데이터 수집 - 2025.03.29
데이터 수집 - 2025.03.28
데이터 수집 - 2025.03.27
데이터 수집 - 2025.03.26
데이터 수집 - 2025.03.25
데이터 수집 - 2025.03.23
데이터 수집 - 2025.03.22
['KIA', 'KT', 'LG', 'NC', 'SSG', '두산', '롯데', '삼성', '키움', '한화']
[[1.    0.5   0.667 0.5   0.4   0.333 0.286 0.375 0.333 0.4   0.364 0.364
  0.333 0.385 0.429 0.4   0.375 0.375 0.412 0.444 0.421]
 [0.    0.5   0.667 0.5   0.6   0.667 0.571 0.571 0.625 0.556 0.5   0.5
  0.455 0.5   0.538 0.5   0.533 0.533 0.563 0.529 0.556]
 [1.    1.    1.    1.    1.    1.    1.    1.    0.875 0.889 0.9   0.9
  0.909 0.917 0.846 0.857 0.867 0.875 0.824 0.833 0.842]
 [0.    0.5   0.333 0.5   0.6   0.5   0.429 0.429 0.429 0.429 0.375 0.444
  0.5   0.455 0.417 0.462 0.429 0.4   0.438 0.438 0.43

In [265]:
kbo_rate_df = pd.DataFrame(result, index=teams)
kbo_rate_df

0    1      2     3    4      5      6      7      8      9   ...  \
KIA  1.0  0.5  0.667  0.50  0.4  0.333  0.286  0.375  0.333  0.400  ...   
KT   0.0  0.5  0.667  0.50  0.6  0.667  0.571  0.571  0.625  0.556  ...   
LG   1.0  1.0  1.000  1.00  1.0  1.000  1.000  1.000  0.875  0.889  ...   
NC   0.0  0.5  0.333  0.50  0.6  0.500  0.429  0.429  0.429  0.429  ...   
SSG  1.0  1.0  0.667  0.75  0.8  0.667  0.571  0.625  0.625  0.625  ...   
두산   0.0  0.0  0.000  0.25  0.2  0.333  0.286  0.250  0.333  0.400  ...   
롯데   0.0  0.0  0.333  0.25  0.2  0.167  0.286  0.286  0.375  0.444  ...   
삼성   1.0  1.0  1.000  0.75  0.6  0.500  0.571  0.625  0.667  0.600  ...   
키움   0.0  0.0  0.000  0.25  0.4  0.500  0.571  0.500  0.444  0.400  ...   
한화   1.0  0.5  0.333  0.25  0.2  0.333  0.429  0.375  0.333  0.300  ...   

        11     12     13     14     15     16     17     18     19     20  
KIA  0.364  0.333  0.385  0.429  0.400  0.375  0.375  0.412  0.444  0.421  
KT   0.500  0.455  0.500  0.538  0.500  0.533  0.533  0.563  0.529  0.556  
LG   0.900  0.909  0.917  0.846  0.857  0.867  0.875  0.824  0.833  0.842  
NC   0.444  0.500  0.455  0.417  0.462  0.429  0.400  0.438  0.438  0.438  
SSG  0.667  0.700  0.636  0.667  0.615  0.643  0.643  0.600  0.563  0.529  
두산   0.417  0.462  0.500  0.467  0.438  0.412  0.389  0.421  0.421  0.421  
롯데   0.455  0.417  0.385  0.357  0.400  0.438  0.471  0.444  0.474  0.500  
삼성   0.583  0.615  0.643  0.600  0.625  0.588  0.588  0.556  0.526  0.500  
키움   0.417  0.385  0.357  0.400  0.375  0.353  0.389  0.368  0.350  0.333  
한화   0.333  0.308  0.286  0.333  0.375  0.412  0.389  0.421  0.450  0.476  

[10 rows x 21 columns]

In [267]:
kbo_rate_df.to_csv('kbo_rate.csv')